### ISSUE TITLE
Clean install fails

### ISSUE THREAD

**Issue by sonnius** [zzamboni/dot-hammerspoon#10]
Hi,

When I follow the install instructions hammerspoon throws an error when loading the configuration:

2017-05-31 11:58:03: -- Loading Spoon: SpoonInstall
2017-05-31 11:58:03: *** ERROR: /Users/rob/.hammerspoon/Spoons/SpoonInstall.spoon/init.lua:381: attempt to index a nil value (field 'spoons')
stack traceback:
	/Users/rob/.hammerspoon/Spoons/SpoonInstall.spoon/init.lua:381: in function 'SpoonInstall.andUse'
	/Users/rob/.hammerspoon/init.lua:35: in main chunk
	[C]: in function 'xpcall'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:561: in function 'hs._coresetup.setup'
	(...tail calls...)

**Comment by irfn** [comment]
Any update on this @zzamboni Looks like we need to do some setup

**Comment by zzamboni** [comment]
@sonnius @irfn sorry about this - I failed to realize (and mention) that SpoonInstall needs the hs.spoons module in Hammerspoon, which is merged into the Hammerspoon master already (https://github.com/Hammerspoon/hammerspoon/pull/1405) but not released yet (it will be in Hammerspoon 0.9.55, see https://github.com/Hammerspoon/hammerspoon/issues/1433). In the meantime, what you can do is fetch the files from https://github.com/Hammerspoon/hammerspoon/tree/master/extensions/spoons and put them in a `~/.hammerspoon/hs/spoons/` directory - this should result in Hammerspoon being able to load it.

Apologies for the confusion!

**Comment by zzamboni** [comment]
@sonnius @irfn I have updated the repository so that hs.spoons is included, but it is only loaded if it's not included in Hammerspoon. Hope this helps!
