### ISSUE TITLE
Notify and execute updates

### ISSUE THREAD

**Issue by tzz** [zzamboni/dot-hammerspoon#2]
I'm not sure if this is feasible but it would be nice:
- when there's a newer version available, there should be an indicator in the menu or wherever
- the indicator should let the user update directly from there, instead of dropping to the command line

**Comment by zzamboni** [comment]
Hey @tzz - sorry for the long delay in responding, somehow I never got (or saw) any GitHub notifications from this repo.

As you may have seen, I have converted the whole OMH setup into Spoons. My [SpoonInstall](http://zzamboni.org/zzSpoons/SpoonInstall.html) spoon has the ability to automatically install spoons from a repository, but it doesn't have a concept of versioning yet. It might not be very hard to add it, and then, new-version notifications should be doable. I may take a stab at this sometime.
