### ISSUE TITLE
clipboard: copy / pasting image not working

### ISSUE THREAD

**Issue by skamsie** [zzamboni/dot-hammerspoon#3]
When I copy an image file and try to paste it somewhere from the hammerspoon clipboard it does not work. It seems that it actually only copies the title as as string.

```

17:01:05                 current_clipboard (text) = mountains.jpg
                         Adding mountains.jpg to clipboard history
17:01:18                 current_clipboard (text) = ocean_view.jpg
                         Adding ocean_view.jpg to clipboard history
17:03:02                 Refreshing chooser choices
                         Storing currently focused window
                         Calling mod.selectorobj:show()
17:04:10                 Refreshing chooser choices
                         Storing currently focused window
                         Calling mod.selectorobj:show()
```

<img width="501" alt="screen shot 2016-04-29 at 5 04 14 pm" src="https://cloud.githubusercontent.com/assets/7014744/14920156/7fbf82f8-0e2c-11e6-8c66-64377e23d79b.png">

**Comment by zzamboni** [comment]
Hi @skamsie - thanks for the feedback. Indeed, image handling never worked properly, and I never took the time to fix it. This OMH plugin has now been converted to the [TextClipboardHistory spoon](http://zzamboni.org/zzSpoons/TextClipboardHistory.html), which explicitly does not handle images. It shouldn't be too hard to add support, but I haven't had the need nor the time. I'll close this issue for now, but please feel free to open an issue (or better yet, a pull request) against https://github.com/Hammerspoon/Spoons
