### ISSUE TITLE
Default configuration not working on Mac OS X Sierra

### ISSUE THREAD

**Issue by ghost** [zzamboni/dot-hammerspoon#8]
When going through the 3 steps and not modifying anything, Hammerspoon reports an error on OSX. It says that the first plugin listed in init.lua cannot be found. Uncommenting that plugin and reloading the configuration will cause the error to be reported for the second (now first) plugin in the list. 

What does the following mean? The sample code is commented out. I have copied it over and also uncommented it but the results are the same. 

> Copy init-local-sample.lua to init-local.lua and modify to change plugin configuration parameters or add your own arbitrary code.

**Comment by sunfarm** [comment]
I very recently discovered Hammerspoon and am exited to use oh-my-hammerspoon to get started with my own configuration. I had this issue as well and it seems to be this line in `oh-my-hammerspoon.lua` not doing what it's intended to do (make the plugins/ directory discoverable).

```
package.path = package.path .. ';plugins/?.lua'
```

I _very_ temporarily fixed it by moving plugin directories I wanted to use into ~/.hammerspoon e.g.

```
cd ~/.hammerspoon
mv plugins/windows .
```

I am also really new to lua and I know this is a stupid fix, but maybe it will help someone for a couple days.

**Comment by zzamboni** [comment]
Hi @databaseline and @sunfarm - thanks for your comments and fixes, and sorry for the delay in responding. In the meantime, OMH has all been converted to a Spoon-based configuration. You can still use the contents of this repo as a starting point, and hopefully it will work better than the previous one. I look forward to your feedback!

**Comment by sunfarm** [comment]
Thanks @zzamboni. I look forward to trying it out!
