### ISSUE TITLE
Specify pasteboard/clipboard item?

### ISSUE THREAD

**Issue by emg80** [zzamboni/dot-hammerspoon#9]
Is there a way to specify a particular pasteboard/clipboard item?

Sorry if this has already been asked, been browsing around for a few hours and can't seem to put together a solution!

The plan is to create a key bind using the num keys to denote each clipboard item [(see image)](http://i.imgur.com/J9pxIQx.png)

What I have so far:
#####################

hs.hotkey.bind({"cmd", "alt", "ctrl"}, "5", function()
hs.eventtap.keyStrokes(hs.pasteboard.getContents())
hs.alert.show("Paste test done")
end)

#####################
Default returns the first item on the pasteboard - Returns/pastes 'A'

Ideally "5" would return/paste 'E' ( "6"='F' , "7"='G' etc)

Noticed you incorporated [VFS's clipboard.lua](https://github.com/VFS/.hammerspoon/blob/master/tools/clipboard.lua) and expanded upon it within OMH (PS, Seems well documented, Thanks!) 

**Note:** Currently using VFS's code within my init.lua. (Haven't gone beyond init.lua, only discovered hs last night!) so I'm not using OMH, or it's /plugins/misc/clipboard.lua just yet. 
An uneducated (I'm not a programmer!) look at the differences between VFS + OHM suggested the majority of the additional code included within OMH (minus a few extra features) allows the code to sit within its own .lua / so it can be called by OMH as required.  

Another reason I'm not using OMH just yet is that I'm unaware if there would be a key bind conflict.

Hopefully my suggestion won't be to difficult to achieve, maybe others may find it useful if included in OMH?

Any help is really appreciated!

**Comment by zzamboni** [comment]
Hi @emg80 - thank you for your feedback! In the meantime all of OMH has been converted to Spoons - the clipboard history is now the [TextClipboardHistory](http://zzamboni.org/zzSpoons/TextClipboardHistory.html) spoon. The Chooser has keyboard shortcuts for the first 9 entries (see attachment). Does this address your problem? Please feel free to file an issue at https://github.com/zzamboni/zzSpoons/issues (where the spoon currently lives) if it does not.
![cursor_and_chooser_and_specify_pasteboard_clipboard_item__ _issue__9_ _zzamboni_dot-hammerspoon](https://cloud.githubusercontent.com/assets/32876/26776085/10c67260-49d8-11e7-919e-5093a0ed2d0b.jpg)
